# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getCorrMatrix <- function(X, param, covType) {
    .Call(`_nestedKriging_getCorrMatrix`, X, param, covType)
}

getCrossCorrMatrix <- function(X1, X2, param, covType) {
    .Call(`_nestedKriging_getCrossCorrMatrix`, X1, X2, param, covType)
}

versionInfo <- function(outputLevel = 0L) {
    .Call(`_nestedKriging_versionInfo`, outputLevel)
}

nestedKrigingDirect <- function(X, Y, clusters, x, covType, param, sd2, krigingType = "simple", tagAlgo = "", numThreadsZones = 1L, numThreads = 16L, verboseLevel = 10L, outputLevel = 1L, globalOptions = as.integer( c(0)), nugget = as.numeric( c(0))) {
    .Call(`_nestedKriging_nestedKrigingDirect`, X, Y, clusters, x, covType, param, sd2, krigingType, tagAlgo, numThreadsZones, numThreads, verboseLevel, outputLevel, globalOptions, nugget)
}

looErrors <- function(X, Y, clusters, indices, covType, param, sd2, krigingType = "simple", tagAlgo = "", numThreadsZones = 1L, numThreads = 16L, verboseLevel = 10L, outputLevel = 1L, globalOptions = as.integer( c(0)), nugget = as.numeric( c(0)), method = "NK") {
    .Call(`_nestedKriging_looErrors`, X, Y, clusters, indices, covType, param, sd2, krigingType, tagAlgo, numThreadsZones, numThreads, verboseLevel, outputLevel, globalOptions, nugget, method)
}

tests_run <- function(showSuccess = FALSE, debugMode = FALSE) {
    .Call(`_nestedKriging_tests_run`, showSuccess, debugMode)
}

tests_getCodeValues <- function(selectedCase, covType = "gauss", forceSimpleKriging = FALSE, increaseParam = 0.0) {
    .Call(`_nestedKriging_tests_getCodeValues`, selectedCase, covType, forceSimpleKriging, increaseParam)
}

tests_getCaseStudy <- function(selectedCase, covType = "gauss") {
    .Call(`_nestedKriging_tests_getCaseStudy`, selectedCase, covType)
}

looErrorsDirect <- function(X, Y, clusters, indices, covType, param, sd2, krigingType = "simple", tagAlgo = "", numThreadsZones = 1L, numThreads = 16L, verboseLevel = 10L, outputLevel = 1L, globalOptions = as.integer( c(0)), nugget = as.numeric( c(0)), method = "NK") {
    .Call(`_nestedKriging_looErrorsDirect`, X, Y, clusters, indices, covType, param, sd2, krigingType, tagAlgo, numThreadsZones, numThreads, verboseLevel, outputLevel, globalOptions, nugget, method)
}

estimParam <- function(X, Y, clusters, q, covType, niter, paramStart, paramLower, paramUpper, sd2, krigingType = "simple", seed = 0L, alpha = 0.602, gamma = 0.101, a = 200, A = 1, c = 0.1, tagAlgo = "", numThreadsZones = 1L, numThreads = 16L, verboseLevel = 10L, globalOptions = as.integer( c(0)), nugget = as.numeric( c(0)), method = "NK") {
    .Call(`_nestedKriging_estimParam`, X, Y, clusters, q, covType, niter, paramStart, paramLower, paramUpper, sd2, krigingType, seed, alpha, gamma, a, A, c, tagAlgo, numThreadsZones, numThreads, verboseLevel, globalOptions, nugget, method)
}

